name:                roman-numerals
version:             0.1.0.0
github:              "githubuser/roman-numerals"
license:             BSD3
author:              "James Pittendreigh"
maintainer:          "james@pittendreigh.co.uk"
copyright:           "2019 James Pittendreigh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/roman-numerals#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- containers
- MissingH

library:
  source-dirs: src

# executables:
#   roman-numerals-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - roman-numerals

tests:
  roman-numerals-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - roman-numerals
    - hspec
